# Generated by Django 4.2.21 on 2025-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_category_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='record',
            name='subcategory',
            field=models.ManyToManyField(to='records.subcategory', verbose_name='Подкатегории'),
        ),
    ]
