# Generated by Django 4.2.21 on 2025-05-29 12:33

import datetime
from django.db import migrations, models
import records.validators


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_record_subcategory_record_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, validators=[records.validators.validate_pub_date], verbose_name='Дата публикации'),
        ),
    ]
