# Generated by Django 4.2.21 on 2025-05-29 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма'),
        ),
    ]
